---
- hosts: zoo
  user: arturskowronski
  connection: local
  vars: 
    project_destination: ~/Projects
    sr_proxy_destination: ~/Projects/smart-proxy

  vars_files:
    - Brew/brew.yml
    - Brew/cask.yml
    - Brew/main.yml
    - Gems/gems.yml
    - Node/node.yml
    - projects.yml

  tasks:
    - name: Tap homebrews.
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: Get list of installed homebrew packages.
      command: brew list
      register: homebrew_list

    - name: Get list of installed ruby gems.
      command: gem list
      register: gems_list

    - name: Install BrewCask 
      command: brew install caskroom/cask/brew-cask
      when: "'brew-cask' not in homebrew_list.stdout"

    - name: Get list of installed cask packages.
      command: brew cask list
      register: homebrew_cask_list

    - name: Install apps via `brew cask`.
      command: brew cask install {{ item }} --appdir={{ homebrew_cask_appdir }}
      with_items: homebrew_cask_apps
      when: "'{{ item }}' not in homebrew_cask_list.stdout"

    - name: Install apps via `brew`.
      command: "brew install {{ item }}"
      with_items: homebrew_installed_packages
      when: "'{{ item }}' not in homebrew_list.stdout"

    - name: Install configured ruby packages.
      command: "gem install {{ item }}"
      with_items: ruby_gems
      when: "'{{ item }}' not in gems_list.stdout"
      sudo: yes

    - name: Install npm packages
      npm: name={{item}} global=yes state=present
      with_items: npm_packages

    - name: Clone Projects
      git: "repo=git@github.com:smartrecruiters/{{ item }} dest={{ project_destination }}/{{ item }} update=no" 
      with_items: sr_projects

    - name: Clone SmartProxy
      git: "repo=git@github.com:smartrecruiters/smart-proxy dest={{ sr_proxy_destination }} update=no" 

    - name: Create Docker Machine
      docker_machine:
          name: sr-docker-machine
          state: present
          driver: virtualbox
          registry: animal:5000
