---
- hosts: zoo
  user: arturskowronski
  connection: local
  vars: 
    project_destination: ~/Projects
    sr_proxy_destination: ~/Projects

  vars_files:
    - Brew/brew.yml
    - Brew/cask.yml
    - Brew/main.yml
    - Gems/gems.yml
    - Node/node.yml
    - projects.yml

  tasks:
    - name: Get list of installed homebrew packages.
      command: brew list
      register: homebrew_list

    - name: Get list of installed ruby gems.
      command: gem list
      register: gems_list

    - name: Install casks 
      command: brew install caskroom/cask/brew-cask
      when: "'brew-cask' not in homebrew_list.stdout"

    - name: Get list of apps installed with cask.
      command: brew cask list
      register: homebrew_cask_list

    - name: Install apps via `brew cask`.
      command: brew cask install {{ item }} --appdir={{ homebrew_cask_appdir }}
      with_items: homebrew_cask_apps
      when: "'{{ item }}' not in homebrew_cask_list.stdout"

    - name: Install configured homebrew packages.
      command: "brew install {{ item }}"
      with_items: homebrew_installed_packages
      when: "'{{ item }}' not in homebrew_list.stdout"

    - name: Install configured ruby packages.
      command: "gem install {{ item }}"
      with_items: ruby_gems
      when: "'{{ item }}' not in gems_list.stdout"

    - name: Install npm packages
      npm: name={{item}} global=yes state=present
      with_items: npm_packages

    - name: Clone SmartProxy
      git: "repo=https://github.com/SmartRecruiters/{{ item }} dest=~/{{ project_destination }} clone=no update=no" 
      with_items: sr_projects

    - name: Clone Projects
      git: "repo=https://github.com/SmartRecruiters/smart-proxy dest=~/{{ sr_proxy_destination }} clone=no update=no" 
